import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ThemeProvider } from "next-themes";
import MotionPageWrapper from "@/components/blocks/motion-page-wrapper";
import { Toaster } from "@/components/ui/sonner";
import { StoreProvider } from "./store";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Emotion Tracker",
  description: "Generated by simple men",
  icons: {
    icon: [
      { url: "/icons/favicon.ico", sizes: "32x32", type: "image/x-icon" },
      { url: "/icons/lotus.png", sizes: "512x512", type: "image/png" },
    ],
    apple: "/icons/apple-touch-icon.png",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ colorScheme: "dark" }}
      suppressHydrationWarning
      className="flex h-svh w-screen items-center justify-center"
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/lotus.png" />
        <link rel="apple-touch-icon" href="/icons/lotus.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full w-screen max-w-[500px] antialiased`}
      >
        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          <Providers>
            <StoreProvider>
              <MotionPageWrapper>
                {children}
                <Toaster />
              </MotionPageWrapper>
            </StoreProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
