import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ThemeProvider } from "next-themes";
import MotionPageWrapper from "@/components/blocks/motion-page-wrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Emotion Tracker",
  description: "Generated by simple men",
  icons: {
    icon: [
      { url: "/icons/favicon.ico", sizes: "16x16", type: "image/ico" },
      { url: "/icons/favicon.ico", sizes: "32x32", type: "image/ico" },
    ],
    apple: "/icons/apple-touch-icon.png",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ colorScheme: "dark" }} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-svh w-screen antialiased`}
      >
        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          <Providers>
            <MotionPageWrapper>{children}</MotionPageWrapper>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
